version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    rebase-strategy: disabled
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
