FROM gcr.io/distroless/static
ARG TARGETOS=linux
ARG TARGETARCH

RUN make build-amd64

COPY bin/external-secrets-${TARGETOS}-${TARGETARCH} /bin/external-secrets

# Run as UID for nobody
USER 65534

ENTRYPOINT ["/bin/external-secrets"]
